#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=58gb,walltime=5:00:00
#PBS -N tractclassification
#PBS -V

rm -rf tracts
rm -rf dtiinit

set -e
set -x

#need to copy dtiinit input to cwd.. because AFQ tries to write stuff to input
#https://github.com/yeatmanlab/AFQ/issues/35
dtiinit_dir=$(jq -r .dtiinit config.json)
chmod -R +rwx $dtiinit_dir

#this worked some place, and didn't work on other placde..
#singularity exec -e -B dtiinit:`realpath $dtiinit_dir` docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main

singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main

if [ ! -s classification.mat ];
then
	echo "output missing"
	exit 1
fi

mkdir -p wmc
mv classification.mat wmc
mv tracts wmc
