#!/bin/bash
#PBS -l nodes=1:ppn=16:dc2,walltime=4:00:00
#PBS -N sca-tractclass
#PBS -V

cd $PBS_O_WORKDIR

module load matlab
module load spm

rm -rf tracts

export MATLABPATH=$MATLABPATH:$SCA_SERVICE_DIR
matlab -nodisplay -nosplash -r main
if [ $? -eq 0 ]; then
    #fake products.json for now..
    echo '{}' > products.json
fi

if [ -s output.mat ];
then
	echo 0 > finished
else
	echo "output missing"
	echo 1 > finished
	exit 1
fi
